spring:
  datasource:
    url: jdbc:postgresql://dpg-copieakf7o1s73e05il0-a.oregon-postgres.render.com:5432/dbname_cvgn
    username: dbname_cvgn_user
    password: GsNjpfXYjNijl9koxpudBg9tdsTTvzdZ

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true